---
# Separated because APB test detect it as a fail when the method exists on the run time
- name: "[MONGODB-APB][{{ mode | upper }}] Encode MongoDB Credentials"
  asb_encode_binding:
    fields:
      DB_TYPE: "{{ service_name }}"
      DB_HOST: "{{ service_name }}"
      DB_PORT: 27017
      DB_USER: "{{ MONGODB_USER }}"
      DB_PASSWORD: "{{ MONGODB_PASSWORD }}"
      DB_NAME: "{{ MONGODB_DATABASE }}"
  when:
    - state == 'present'
