---
- name: "[MONGODB-APB][{{ mode | upper }}] Create ImageStream for MongoDB image"
  openshift_v1_image_stream:
    state: "{{ state }}"
    name: "{{ app_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ service_name }}"
      name: "{{ service_name }}"
    lookup_policy_local: False
    tags:
      - name: "{{ mongodb_image_tag }}"
    docker_image_repository: "{{ mongodb_image }}"
  register: mongod_is

- name: "[MONGODB-APB][{{ mode | upper }}] Set to {{ state }} MongoDB PVC for Persistent plan"
  k8s_v1_persistent_volume_claim:
    state: "{{ state }}"
    name: "{{ item.name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: "{{ item.size }}Gi"
  with_items:
    - { name: "{{ mongodb_data_pvc_name }}", size: "{{ MONGODB_DATA_STORAGE_SIZE }}" }
  register: mongodb_pvc
  when: _apb_plan_id == 'persistent'

- debug:
    var: mongodb_image

- name: "[MONGODB-APB][{{ mode | upper }}] Set to {{ state }} the MongoDB Deployment Config for Ephemeral plan"
  openshift_v1_deployment_config:
    state: "{{ state }}"
    name: "{{ service_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    replicas: 1
    selector:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    strategy_type: Rolling
    strategy_rolling_params:
      interval_seconds: 1
      max_surge: 25%
      max_unavailable: 25%
      timeout_seconds: 600
      update_period_seconds: 1
    spec_template_metadata_labels:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    containers:
      - env:
          - name: MONGODB_ADMIN_PASSWORD
            value: "{{ MONGODB_ADMIN_PASSWORD }}"
          - name: MONGODB_PASSWORD
            value: "{{ MONGODB_PASSWORD }}"
          - name: MONGODB_USER
            value: "{{ MONGODB_USER }}"
          - name: MONGODB_DATABASE
            value: "{{ MONGODB_DATABASE }}"
        name: "{{ service_name }}"
        image: "{{ mongodb_image }}"
        image_pull_policy: IfNotPresent
        liveness_probe:
          initial_delay_seconds: 30
          tcp_socket:
            port: 27017
          timeout_seconds: 1
        readiness_probe:
          exec:
            command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - "mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval='quit()'"
          initial_delay_seconds: 3
          timeout_seconds: 1
        ports:
          - container_port: 27017
            protocol: TCP
        volume_mounts:
          - mount_path: "{{ mongodb_data_path }}"
            name: "{{ mongodb_data_volume_name }}"
    volumes:
      - name: "{{ mongodb_data_volume_name }}"
        emptyDir: []
    dns_policy: ClusterFirst
    restart_policy: Always
    termination_grace_period_seconds: 30
    test: false
    triggers:
      - type: ConfigChange
  register: mongod_dc
  when: _apb_plan_id == 'ephemeral'

- name: "[MONGODB-APB][{{ mode | upper }}] Set to {{ state }} the MongoDB Deployment Config for Persistent plan"
  openshift_v1_deployment_config:
    state: "{{ state }}"
    name: "{{ service_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    replicas: 1
    selector:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    strategy_type: Rolling
    strategy_rolling_params:
      interval_seconds: 1
      max_surge: 25%
      max_unavailable: 25%
      timeout_seconds: 600
      update_period_seconds: 1
    spec_template_metadata_labels:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    containers:
      - env:
          - name: MONGODB_ADMIN_PASSWORD
            value: "{{ MONGODB_ADMIN_PASSWORD }}"
          - name: MONGODB_PASSWORD
            value: "{{ MONGODB_PASSWORD }}"
          - name: MONGODB_USER
            value: "{{ MONGODB_USER }}"
          - name: MONGODB_DATABASE
            value: "{{ MONGODB_DATABASE }}"
        name: "{{ service_name }}"
        image: "{{ mongodb_image }}"
        image_pull_policy: IfNotPresent
        liveness_probe:
          initial_delay_seconds: 30
          tcp_socket:
            port: 27017
          timeout_seconds: 1
        readiness_probe:
          exec:
            command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - "mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval=\"quit()\""
        initial_delay_seconds: 3
        timeout_seconds: 1
        ports:
          - container_port: 27017
            protocol: TCP
        volume_mounts:
          - mount_path: "{{ mongodb_data_path }}"
            name: "{{ mongodb_data_volume_name }}"
    volumes:
      - name: "{{ mongodb_data_volume_name }}"
        persistent_volume_claim:
          claim_name: "{{  mongodb_data_pvc_name }}"
    dns_policy: ClusterFirst
    restart_policy: Always
    termination_grace_period_seconds: 30
    test: false
    triggers:
      - type: ConfigChange
  register: mongod_dc
  when: _apb_plan_id == 'persistent'

- name: "[MONGODB-APB][{{ mode | upper }}] Set to {{ state }} the MongoDB Service"
  k8s_v1_service:
    name: "{{ service_name }}"
    namespace: "{{ namespace }}"
    labels:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    selector:
      app: "{{ service_name }}"
      service: "{{ service_name }}"
    ports:
    - name: "{{ service_name }}-27017"
      port: 27017
      protocol: TCP
      target_port: 27017
    state: "{{ state }}"
  register: mongodb_svc

- name: "[MONGODB-APB][{{ mode | upper }}] Wait for MongoDB to be ready"
  wait_for:
    port: 27017
    host: "{{ mongodb_svc.service.spec.cluster_ip }}"
    timeout: 300
  when: state == "present"


